### ISSUE TITLE
Improve online documentation

### ISSUE THREAD

**Issue by natj** [natj/runko#23]
Documentation can be easily improved by adding `README.md`s into the module folders. There we could list all the design principles and submodules.

**Comment by StanczakDominik** [comment]
READMEs work, but perhaps it would be better (though obviously, more effort) to add an actual online documentation (say, via GitHub pages/ReadTheDocs and Sphinx - as done by [PIConGPU](https://picongpu.readthedocs.io/en/0.4.3/) or [SMILEI](https://smileipic.github.io/tutorials/basics_weibel_twostream.html) ).

Some basic examples of running and visualizing the simulations would also go a long way in making plasmabox more accessible.

**Comment by StanczakDominik** [comment]
I just found https://github.com/natj/plasmabox/tree/master/projects/tests - that's a good start! I'm definitely going to play with those a bit. Perhaps wrapping those in jupyter notebooks and adding some narrative could help - and those could then be put into docs via, say, sphinx-gallery.

**Comment by natj** [comment]
Start with a `projects/shocks` first :) That should work out-of-the-box.

Jupyter notebook does not help in this case because these things are supposedly run on the cluster via SLURM or similar. 

Sphinx is definitely something I was planning on adding. I actually already have some notes ready that should be imported there when I have time.

**Comment by natj** [comment]
Closing this since I now added documentation to `docs/` and deployed with sphinx into  [runko.readthedocs.io](https://runko.readthedocs.io).
